function cycling_gui
    paramdesc = struct(...
                'pressuremeasurementsperstep','Number of pressure/resistance measurements per data point', ...
                'minvalue','Minimum duty cycle (0 - 1)', ...
                'maxvalue','Maximum duty cycle (0 - 1)', ...
                'numsteps','Number of data points in one direction (total = 2*numsteps*cycles+1)', ...
                'cycles','Number of cycles', ...               
                'serialport','Serial port to use',...
                'devicename','NI DMM Device name',...
                'dataroot','Directory save data');
    
    showexperimentgui(paramdesc,@cycling_experiment);                     
end