function cycling_gui
    paramdesc = struct(...
                'n','Number of pressure/resistance measurements per data point', ...
                'minvalue','Minimum duty cycle (0 - 1)', ...
                'maxvalue','Maximum duty cycle (0 - 1)', ...
                'm','m = Number of data points in one direction (total = 2*m+1)', ...
                'cycles','Number of cycles', ...
                'photofreq','Data points after photo is taken (0 = never take a photo, 1 = after every data point)', ...
                'resistancebits','Number of bits in resistance measurement', ...
                'resistancerange','Range of the resistance measurement, in Ohms', ...
                'ramp','Ramp duty cycle (0 = no, 1 = yes)', ...
                'ramppause','If ramping, what is the pause between one step of duty cycle (seconds)', ...
                'pause','Pause after adjusting duty cycle (seconds)', ...              
                'autosave','Autosave after this many data points',...
                'serialport','Serial port to use',...
                'devicename','NI DMM Device name',...
                'temperature','Record temperature (0 = no, 1 = yes)',...
                'temperaturedevicename','NI USB TC-01 Device name',...
                'dataroot','Directory save data');
    
    showexperimentgui(paramdesc,@cycling_experiment);                     
end