function demo_gui
    paramdesc = struct(...
                'resistancebits','Number of bits in resistance measurement', ...
                'resistancerange','Range of the resistance measurement, in Ohms', ...
                'autosave','Autosave after this many data points',...
                'serialport','Serial port to use',...
                'devicename','NI DMM Device name',...
                'temperature','Record temperature (0 = no, 1 = yes)',...
                'temperaturedevicename','NI USB TC-01 Device name',...
                'dataroot','Directory save data',...
                'n','Number of resistance repetitions',...
                'steptime','Each program step takes this many seconds');
                
    showexperimentgui(paramdesc,@demo_experiment);                     
end