function demo_multichannel_gui
    paramdesc = struct(...
                'strainfreq','Frequency of strain measurements', ...
                'autosave','Autosave after this many data points',...
                'serialport','Serial port to use',...
                'devicename','NI CompactDaq Device name',...
                'temperature','Record temperature (0 = no, 1 = yes)',...
                'temperaturedevicename','NI USB TC-01 Device name',...
                'dataroot','Directory save data',...
                'n','Number of pressure repetitions',...
                'steptime','Each program step takes this many seconds');
                
    showexperimentgui(paramdesc,@demo_multichannel_experiment);                     
end